import {
  handleContextAssemble,
  handleContextConflictAccept,
  handleContextConflictReject,
  handleContextConflicts,
  handleContextEdges,
  handleContextIngestEvent,
  handleContextInternalize,
  handleContextQueryGraph,
  handleProjectGraphAddOverlay,
  handleProjectGraphExplainNode,
  handleProjectGraphBlastRadius,
  handleProjectGraphGetNeighbors,
  handleProjectGraphGetNode,
  handleProjectGraphPath,
  handleProjectGraphQuery,
  handleProjectGraphReindex,
  handleProjectGraphTaskQuery,
} from './handlers.js';
import {
  ContextAssembleSchema,
  ContextConflictAcceptSchema,
  ContextConflictRejectSchema,
  ContextConflictsSchema,
  ContextEdgesSchema,
  ContextIngestEventSchema,
  ContextInternalizeSchema,
  ContextQueryGraphSchema,
  ProjectGraphNeighborsSchema,
  ProjectGraphNodeSchema,
  ProjectGraphBlastRadiusSchema,
  ProjectGraphOverlaySchema,
  ProjectGraphPathSchema,
  ProjectGraphQuerySchema,
  ProjectGraphReindexSchema,
  ProjectGraphTaskQuerySchema,
} from './tool-schemas.js';
import { defineTool } from './tool-types.js';

export const contextTools = [
  defineTool({
    name: 'context_ingest_event',
    description: 'Ingest a low-level ECS context event and materialize it as an episode node.',
    schema: ContextIngestEventSchema,
    handler: (api, input) => handleContextIngestEvent(api, input),
  }),
  defineTool({
    name: 'context_query_graph',
    description: 'Query ECS context graph nodes directly.',
    schema: ContextQueryGraphSchema,
    handler: (api, input) => handleContextQueryGraph(api, input),
  }),
  defineTool({
    name: 'context_edges',
    description: 'List ECS graph edges and relationships.',
    schema: ContextEdgesSchema,
    handler: (api, input) => handleContextEdges(api, input),
  }),
  defineTool({
    name: 'context_conflicts',
    description: 'List active ECS conflict records for a project or the entire graph.',
    schema: ContextConflictsSchema,
    handler: (api, input) => handleContextConflicts(api, input),
  }),
  defineTool({
    name: 'context_conflict_accept',
    description: 'Accept a reflected conflict-resolution candidate and mark the source conflict resolved.',
    schema: ContextConflictAcceptSchema,
    handler: (api, input) => handleContextConflictAccept(api, input),
  }),
  defineTool({
    name: 'context_conflict_reject',
    description: 'Reject a reflected conflict-resolution candidate without resolving the source conflict.',
    schema: ContextConflictRejectSchema,
    handler: (api, input) => handleContextConflictReject(api, input),
  }),
  defineTool({
    name: 'context_assemble',
    description: 'Assemble a full working context for a task. Returned text includes a "Project Graph Relationships" section (file/module/dependency/asset facts seeded by `currentFile` plus 1-hop neighbours) and a "Retrieval Tickets" block; you MUST call `memory_feedback_auto` once per ticket after answering, marking each as adopted/partial/ignored/rejected so the graph learns which nodes actually informed your answer.',
    schema: ContextAssembleSchema,
    handler: (api, input) => handleContextAssemble(api, input),
  }),
  defineTool({
    name: 'context_internalize',
    description: 'Generate or accept internalization suggestions from stable ECS knowledge.',
    schema: ContextInternalizeSchema,
    handler: (api, input) => handleContextInternalize(api, input),
  }),
  defineTool({
    name: 'query_project_graph',
    description: 'Search Mindstrate project graph nodes and return bounded evidence-backed context.',
    schema: ProjectGraphQuerySchema,
    handler: (api, input) => handleProjectGraphQuery(api, input),
  }),
  defineTool({
    name: 'query_project_graph_task',
    description: 'Run a task-oriented graph query such as entry-points, before-edit, binding, asset-references, flow, impact, module, or explain.',
    schema: ProjectGraphTaskQuerySchema,
    handler: (api, input) => handleProjectGraphTaskQuery(api, input),
  }),
  defineTool({
    name: 'get_project_graph_node',
    description: 'Retrieve one project graph node with provenance and evidence.',
    schema: ProjectGraphNodeSchema,
    handler: (api, input) => handleProjectGraphGetNode(api, input),
  }),
  defineTool({
    name: 'get_project_graph_neighbors',
    description: 'Return bounded incoming and outgoing project graph edges around one node.',
    schema: ProjectGraphNeighborsSchema,
    handler: (api, input) => handleProjectGraphGetNeighbors(api, input),
  }),
  defineTool({
    name: 'explain_project_graph_node',
    description: 'Explain why a project graph node matters using stored evidence and local graph edges.',
    schema: ProjectGraphNodeSchema,
    handler: (api, input) => handleProjectGraphExplainNode(api, input),
  }),
  defineTool({
    name: 'get_project_graph_path',
    description: 'Find a bounded shortest path between two project graph nodes or files.',
    schema: ProjectGraphPathSchema,
    handler: (api, input) => handleProjectGraphPath(api, input),
  }),
  defineTool({
    name: 'get_project_graph_blast_radius',
    description: 'Estimate local blast radius around a project graph node before editing.',
    schema: ProjectGraphBlastRadiusSchema,
    handler: (api, input) => handleProjectGraphBlastRadius(api, input),
  }),
  defineTool({
    name: 'add_project_graph_overlay',
    description: 'Attach an editable user/team note, correction, confirmation, rejection, risk, or convention to a project graph node or edge without mutating extracted graph facts.',
    schema: ProjectGraphOverlaySchema,
    handler: (api, input) => handleProjectGraphAddOverlay(api, input),
  }),
  defineTool({
    name: 'reindex_project_graph',
    description: 'Rescan the project filesystem and rebuild the project graph. Run this when `before-edit` / `impact` / `context_assemble` start returning stale facts — typical triggers are: the original `mindstrate setup` predates large source root additions, you renamed/moved files outside the editor, or you switched branches. Local mode only; team-server projects are reindexed by the team server itself.',
    schema: ProjectGraphReindexSchema,
    handler: (api, input) => handleProjectGraphReindex(api, input),
  }),
];
